logging:
    level:
        org:
            springframework: WARN
            hibernate: WARN
        com:
            hendisantika: DEBUG
spring:
    freemarker:
        template-loader-path: /WEB-INF/ftl
    expose-request-attributes: true
    expose-spring-macro-helpers: true

server: 
    #port: 80
    port: 9001
    #port: 443
    ssl:
        enabled: true
        client-auth: need
        key-store: classpath:client.jks
        key-store-password: arep2019
        key-alias: client
        key-store-type: JKS
        key-store-provider: SUN
        trust-store: classpath:client.jks
        trust-store-password: arep2019
        trust-store-type: JKS
endpoint:
    serverData: https://localhost:9002/server/data